packages:
  - .

extra-deps:
  - text-format-0.3.2
  - Diff-0.3.4
  - git: https://github.com/ucsd-progsys/liquidhaskell
    commit: 60cdcab03a47a28a6f564bf30ddd5d44b5e3244a
    subdirs:
      - .
      - liquid-base
      - liquid-ghc-prim
      - liquid-containers
      - liquid-prelude
  - git: https://github.com/ucsd-progsys/liquid-fixpoint
    commit: 9c8640a469b157d8f561307718e34ae131e9c7c4

resolver: nightly-2021-06-01
# resolver: lts-17.5
# compiler: ghc-9.0.1
# allow-newer: true
