packages:
  - .

extra-deps:
#  - liquidhaskell-0.8.10.2
#  - liquid-base-4.14.1.0
#  - liquid-containers-0.6.2.1
#  - liquid-ghc-prim-0.6.1
  - Diff-0.3.4
  - git: https://github.com/ucsd-progsys/liquidhaskell
    commit: d9155afac5e4c477c1555f855cf26af4ae018006 
    subdirs:
      - .
      - liquid-base
      - liquid-ghc-prim
      - liquid-containers
      - liquid-prelude
  - git: https://github.com/ucsd-progsys/liquid-fixpoint
    commit: ec3ef7993a5b2f3155a583fec5d13dd8ce3385c9

resolver: nightly-2021-06-01
allow-newer: true
