packages:
  - .

extra-deps:
  - Diff-0.3.4
  # - git: https://github.com/ucsd-progsys/liquidhaskell
  - git: https://github.com/TenStrings/liquidhaskell
    commit: 247f79fc291244553673cf8a48e9aaa50d2b6a4c 
    subdirs:
      - .
      - liquid-base
      - liquid-ghc-prim
      - liquid-containers
      - liquid-prelude
  - git: https://github.com/ucsd-progsys/liquid-fixpoint
    commit: b91e279b8dd3a4716372692d2126ffcb90f5e5a3 
  - git: https://github.com/zgrannan/rest
    commit: 1cadb23edfbc393245ae964315b07f5c8581ea9f
  - hashable-1.3.0.0@sha256:d60cad00223d46172020c136e68acef0481a47d0302b2e74b1805b4f3a446a9b,5389
  # - linear-base-0.1.0@sha256:3c0e27562e0f4b23f6f004b2c853350a67e59554f0c8bcf6c1fbf4237686dbad,5469

 
resolver: nightly-2022-03-10
compiler: ghc-8.10.7

allow-newer: true
